module.exports = {
    nodes: [
        {id: 0, name: 'Company A'},
        {id: 1, name: 'Company B'},
        {id: 2, name: 'Company C'},
        {id: 3, name: 'Company D'},
        {id: 4, name: 'Company E'},
        {id: 5, name: 'Company F'},
        {id: 6, name: 'Company G'},
        {id: 6, name: 'Company H'},
        {id: 7, name: 'Company I'},
        {id: 8, name: 'Company J'},
        {id: 9, name: 'Company K'},
        {id: 10, name: 'Company L'},
        {id: 11, name: 'Company M'},
        {id: 12, name: 'Company N'},
        {id: 13, name: 'Company O'},
        {id: 14, name: 'Company P'},
        {id: 15, name: 'Company Q'},
        {id: 16, name: 'Company R'},
        {id: 17, name: 'Company S'},
        {id: 18, name: 'Company T'},
        {id: 19, name: 'Company U'},
        {id: 20, name: 'Company V'},
        {id: 21, name: 'Company W'},
        {id: 22, name: 'Company X'},
        {id: 23, name: 'Company Y'},
        {id: 24, name: 'Company Z'},
    ],

    links: [
        {src: 1, dst: 2, label: '10%'},
        {src: 2, dst: 3, label: '20%'},
        {src: 2, dst: 4, label: '30%'},
        {src: 2, dst: 6, label: '40%'},
        {src: 3, dst: 5, label: '50%'},
        {src: 4, dst: 7, label: '60%'},
        {src: 6, dst: 8, label: '70%'},
        {src: 7, dst: 9, label: '80%'},
        {src: 9, dst: 10, label: '90%'},
    ]
};